"""Stable public SDK facade for EasyAgent."""

from .agents import (
    AgentExecutionServices,
    AgentInvocationPhase,
    AgentInvocationState,
    BaseAgent,
    BaseAgentExecutor,
    BasicAgent,
    ConversationHistory,
    DefaultAgentExecutor,
)
from .callbacks import (
    BaseCallback,
    CallbackEvent,
    CallbackManager,
    LoggingCallback,
    MetricsCallback,
    StreamingCallback,
)
from .codeintel import CachedFileEntry, CachedQueryEntry, CodeIntelManager, CodeIntelProvider, WorkspaceCodeIntelCache
from .config import Config
from .context import ContextManager
from .guardrails import (
    DangerousCommandGuardrail,
    PromptInjectionGuardrail,
    SecretLeakGuardrail,
    build_default_hook_manager,
    install_default_guardrails,
)
from .hooks import BaseHook, HookAction, HookDecision, HookExecutionResult, HookManager
from .llms import EasyLLM
from .mcp import (
    MCPAuthConfig,
    MCPCapabilitySnapshot,
    MCPClient,
    MCPConnectionManager,
    MCPConnectionState,
    MCPHub,
    MCPPolicyContext,
    MCPPolicyDecision,
    MCPPolicyError,
    MCPPolicyRule,
    MCPRuntimeManager,
    MCPServerCache,
    MCPToolManager,
    register_mcp_tools,
)
from .metamessages import (
    BaseMetaMessageManager,
    MetaMessage,
    MetaMessageCondition,
    MetaMessageContent,
    MetaMessageContext,
    MetaMessageEvent,
    MetaMessageFactory,
    MetaMessageHistoryPort,
    MetaMessageInjection,
    MetaMessageLifecycle,
    MetaMessageManager,
)
from .observability import (
    AgentInvoke,
    AgentInvokeStats,
    BaseObservabilityManager,
    BaseObservabilityStore,
    EvalCase,
    EvalResult,
    InMemoryObservabilityStore,
    LLMInvoke,
    LLMInvokeStats,
    ObservabilityManager,
    OfflineEvalHarness,
    SQLiteObservabilityStore,
)
from .permissions import (
    PermissionBehavior,
    PermissionContext,
    PermissionDecision,
    PermissionEngine,
    PermissionMode,
    PermissionRule,
    PermissionStore,
    RiskCategory,
)
from .plans import BasePlanMode, ExecutionMode, PlanModeConfig, PlanModeManager, PlanModeState
from .prompting import BaseSystemPromptComposer, PromptBlock, PromptBuildContext, PromptPlacement, SystemPromptComposer, SystemPromptTemplate
from .runtime import (
    AgentStreamEvent,
    AgentStreamEventType,
    BaseMultiAgentRuntime,
    ExecutionContext,
    MultiAgentRuntime,
    RuntimeEvent,
    RuntimeEventBus,
    RuntimeEventType,
    TeamManager,
)
from .session import ConversationStore, SessionRestoreReport, SessionStore
from .skills import SkillManager, SkillManifest, SkillTool
from .tasks import TaskRecord, TaskService, TaskStatus
from .tools import Tool, ToolConflictPolicy, ToolRegistry, ToolResult, ToolSpec
from .training import (
    SuccessfulAgentInvokeFilter,
    TrainingDataFilter,
    TrainingDataFormat,
    TrainingExporter,
    TrainingExportReport,
)
from .worktree import GitWorktreeInfo, GitWorktreeSession, WorktreeManager
from .version import __version__

__all__ = [
    "__version__",
    "AgentInvoke",
    "AgentInvokeStats",
    "AgentExecutionServices",
    "AgentInvocationPhase",
    "AgentInvocationState",
    "AgentStreamEvent",
    "AgentStreamEventType",
    "BaseAgent",
    "BaseAgentExecutor",
    "BaseCallback",
    "BaseHook",
    "BaseMetaMessageManager",
    "BaseMultiAgentRuntime",
    "BaseObservabilityManager",
    "BasePlanMode",
    "BaseSystemPromptComposer",
    "BasicAgent",
    "ConversationHistory",
    "CachedFileEntry",
    "CachedQueryEntry",
    "CallbackEvent",
    "CallbackManager",
    "CodeIntelManager",
    "CodeIntelProvider",
    "Config",
    "ContextManager",
    "ConversationStore",
    "DangerousCommandGuardrail",
    "DefaultAgentExecutor",
    "EasyLLM",
    "EvalCase",
    "EvalResult",
    "ExecutionContext",
    "ExecutionMode",
    "HookAction",
    "HookDecision",
    "HookExecutionResult",
    "HookManager",
    "MCPAuthConfig",
    "MCPCapabilitySnapshot",
    "MCPClient",
    "MCPConnectionManager",
    "MCPConnectionState",
    "MCPHub",
    "MCPPolicyContext",
    "MCPPolicyDecision",
    "MCPPolicyError",
    "MCPPolicyRule",
    "MCPRuntimeManager",
    "MCPServerCache",
    "MCPToolManager",
    "MetaMessage",
    "MetaMessageCondition",
    "MetaMessageContent",
    "MetaMessageContext",
    "MetaMessageEvent",
    "MetaMessageFactory",
    "MetaMessageHistoryPort",
    "MetaMessageInjection",
    "MetaMessageLifecycle",
    "MetaMessageManager",
    "BaseObservabilityStore",
    "InMemoryObservabilityStore",
    "LLMInvoke",
    "LLMInvokeStats",
    "ObservabilityManager",
    "OfflineEvalHarness",
    "PermissionBehavior",
    "PermissionContext",
    "PermissionDecision",
    "PermissionEngine",
    "PermissionMode",
    "PermissionRule",
    "PermissionStore",
    "PlanModeConfig",
    "PlanModeManager",
    "PlanModeState",
    "LoggingCallback",
    "MetricsCallback",
    "MultiAgentRuntime",
    "PromptInjectionGuardrail",
    "PromptBlock",
    "PromptBuildContext",
    "PromptPlacement",
    "RiskCategory",
    "RuntimeEvent",
    "RuntimeEventBus",
    "RuntimeEventType",
    "SQLiteObservabilityStore",
    "SecretLeakGuardrail",
    "SessionRestoreReport",
    "SessionStore",
    "SkillManager",
    "SkillManifest",
    "SkillTool",
    "TaskRecord",
    "TaskService",
    "TaskStatus",
    "TeamManager",
    "SuccessfulAgentInvokeFilter",
    "TrainingDataFilter",
    "TrainingDataFormat",
    "TrainingExporter",
    "TrainingExportReport",
    "Tool",
    "ToolConflictPolicy",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "GitWorktreeInfo",
    "GitWorktreeSession",
    "SystemPromptComposer",
    "StreamingCallback",
    "SystemPromptTemplate",
    "WorktreeManager",
    "WorkspaceCodeIntelCache",
    "build_default_hook_manager",
    "install_default_guardrails",
    "register_mcp_tools",
]
