"""Stable public code intelligence exports."""

from codeintel import (
    CachedFileEntry,
    CachedQueryEntry,
    CodeIntelAvailability,
    CodeIntelManager,
    CodeIntelProvider,
    CodeIntelQueryResult,
    CodeLocation,
    CodePosition,
    CodeRange,
    DEFAULT_FALLBACK_TOOLS,
    DefinitionQuery,
    DiagnosticRecord,
    DiagnosticsQuery,
    DocumentSymbolsQuery,
    LSPClient,
    LSPClientError,
    LSPCodeIntelProvider,
    ReferenceQuery,
    SymbolRecord,
    WorkspaceCodeIntelCache,
    WorkspaceSymbolsQuery,
    path_to_uri,
    uri_to_path,
)

__all__ = [
    "CachedFileEntry",
    "CachedQueryEntry",
    "CodeIntelAvailability",
    "CodeIntelManager",
    "CodeIntelProvider",
    "CodeIntelQueryResult",
    "CodeLocation",
    "CodePosition",
    "CodeRange",
    "DEFAULT_FALLBACK_TOOLS",
    "DefinitionQuery",
    "DiagnosticRecord",
    "DiagnosticsQuery",
    "DocumentSymbolsQuery",
    "LSPClient",
    "LSPClientError",
    "LSPCodeIntelProvider",
    "ReferenceQuery",
    "SymbolRecord",
    "WorkspaceCodeIntelCache",
    "WorkspaceSymbolsQuery",
    "path_to_uri",
    "uri_to_path",
]
